
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mateusz
 */
public class Konwerter extends javax.swing.JFrame {
    double Euro = 4.2;
    double Dolar = 4.0;
    double Rubel = 1.5;
    double Zloty = 1.0;
    /**
     * Creates new form Konwerter
     */
    public Konwerter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        walutyZlewej = new javax.swing.ButtonGroup();
        walutyZprawej = new javax.swing.ButtonGroup();
        przeliczWprawo = new javax.swing.JButton();
        wejscie = new javax.swing.JTextField();
        wyjscie = new javax.swing.JTextField();
        naEuroWprawo = new javax.swing.JRadioButton();
        naDolaryWprawo = new javax.swing.JRadioButton();
        naRubleWprawo = new javax.swing.JRadioButton();
        naZłoteWprawo = new javax.swing.JRadioButton();
        naZłoteWlewo = new javax.swing.JRadioButton();
        naEuroWlewo = new javax.swing.JRadioButton();
        naDolaryWlewo = new javax.swing.JRadioButton();
        naRubleWlewo = new javax.swing.JRadioButton();
        przeliczWlewo = new javax.swing.JButton();
        walutaLewo = new javax.swing.JLabel();
        walutaPrawo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        przeliczWprawo.setText("Przelicz >>");
        przeliczWprawo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przeliczWprawoActionPerformed(evt);
            }
        });

        wejscie.setText("0");
        wejscie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wejscieActionPerformed(evt);
            }
        });

        wyjscie.setText("0");
        wyjscie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjscieActionPerformed(evt);
            }
        });

        walutyZlewej.add(naEuroWprawo);
        naEuroWprawo.setText("Euro");
        naEuroWprawo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naEuroWprawoActionPerformed(evt);
            }
        });

        walutyZlewej.add(naDolaryWprawo);
        naDolaryWprawo.setText("Dolary");
        naDolaryWprawo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naDolaryWprawoActionPerformed(evt);
            }
        });

        walutyZlewej.add(naRubleWprawo);
        naRubleWprawo.setText("Ruble");
        naRubleWprawo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naRubleWprawoActionPerformed(evt);
            }
        });

        walutyZlewej.add(naZłoteWprawo);
        naZłoteWprawo.setText("Złoty");
        naZłoteWprawo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naZłoteWprawoActionPerformed(evt);
            }
        });

        walutyZprawej.add(naZłoteWlewo);
        naZłoteWlewo.setText("Złoty");
        naZłoteWlewo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naZłoteWlewoActionPerformed(evt);
            }
        });

        walutyZprawej.add(naEuroWlewo);
        naEuroWlewo.setText("Euro");
        naEuroWlewo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naEuroWlewoActionPerformed(evt);
            }
        });

        walutyZprawej.add(naDolaryWlewo);
        naDolaryWlewo.setText("Dolary");
        naDolaryWlewo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naDolaryWlewoActionPerformed(evt);
            }
        });

        walutyZprawej.add(naRubleWlewo);
        naRubleWlewo.setText("Ruble");
        naRubleWlewo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naRubleWlewoActionPerformed(evt);
            }
        });

        przeliczWlewo.setText("Przelicz <<");
        przeliczWlewo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przeliczWlewoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(naZłoteWprawo)
                    .addComponent(naRubleWprawo)
                    .addComponent(przeliczWprawo)
                    .addComponent(naEuroWprawo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(wejscie, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(walutaLewo))
                    .addComponent(naDolaryWprawo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(przeliczWlewo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(wyjscie, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(naEuroWlewo)
                            .addComponent(naRubleWlewo)
                            .addComponent(naZłoteWlewo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(walutaPrawo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(naDolaryWlewo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wejscie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wyjscie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(walutaLewo)
                    .addComponent(walutaPrawo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(naZłoteWprawo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(naZłoteWlewo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naEuroWprawo)
                    .addComponent(naEuroWlewo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naDolaryWprawo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(naDolaryWlewo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(naRubleWlewo)
                    .addComponent(naRubleWprawo))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(przeliczWprawo)
                    .addComponent(przeliczWlewo))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wejscieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wejscieActionPerformed
        
    }//GEN-LAST:event_wejscieActionPerformed

    private void przeliczWprawoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przeliczWprawoActionPerformed
        
        double wybranyPrzelicznik = wyborPrzelicznikaZprawej()/wyborPrzelicznikaZlewej();
        String kwota_str = wejscie.getText();
        if(kwota_str.equals("")){
            wyjscie.setText("Nic nie wpisano");
        }
        else {
            try{
                DecimalFormat df = new DecimalFormat("0.00");
                double kwota = df.parse(kwota_str).doubleValue();
                wyjscie.setText(""+df.format(kwota/wybranyPrzelicznik));
            }catch(NumberFormatException ex){
                wyjscie.setText("DUPA");
            } catch (ParseException ex) {
                Logger.getLogger(Konwerter.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_przeliczWprawoActionPerformed

    private void wyjscieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjscieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wyjscieActionPerformed

    private void naEuroWprawoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naEuroWprawoActionPerformed
        String waluta = "";
        if(naEuroWprawo.isSelected()) 
        walutaLewo.setText(naEuroWprawo.getText());    
    }//GEN-LAST:event_naEuroWprawoActionPerformed

    private void naZłoteWprawoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naZłoteWprawoActionPerformed
        String waluta = "";
        if(naZłoteWprawo.isSelected()) 
        walutaLewo.setText(naZłoteWprawo.getText());
    }//GEN-LAST:event_naZłoteWprawoActionPerformed
  
    private void przeliczWlewoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przeliczWlewoActionPerformed
            double wybranyPrzelicznik = wyborPrzelicznikaZlewej()/wyborPrzelicznikaZprawej();
        String kwota_str = wyjscie.getText();
        if(kwota_str.equals("")){
            wejscie.setText("Nic nie wpisano");
        }
        else {
            try{
                DecimalFormat df = new DecimalFormat("0.00");
                double kwota = df.parse(kwota_str).doubleValue();
                wejscie.setText(""+df.format(kwota/wybranyPrzelicznik));
            }catch(NumberFormatException ex){
                wejscie.setText("DUPA");
            }   catch (ParseException ex) {
                    Logger.getLogger(Konwerter.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        }
    }//GEN-LAST:event_przeliczWlewoActionPerformed

    private void naDolaryWprawoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naDolaryWprawoActionPerformed
        String waluta = "";
        if(naDolaryWprawo.isSelected()) 
        walutaLewo.setText(naDolaryWprawo.getText()); 
    }//GEN-LAST:event_naDolaryWprawoActionPerformed

    private void naRubleWprawoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naRubleWprawoActionPerformed
        String waluta = "";
        if(naRubleWprawo.isSelected()) 
        walutaLewo.setText(naRubleWprawo.getText()); 
    }//GEN-LAST:event_naRubleWprawoActionPerformed

    private void naZłoteWlewoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naZłoteWlewoActionPerformed
        String waluta = "";
        if(naZłoteWlewo.isSelected()) 
        walutaPrawo.setText(naZłoteWlewo.getText()); 
    }//GEN-LAST:event_naZłoteWlewoActionPerformed

    private void naEuroWlewoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naEuroWlewoActionPerformed
        String waluta = "";
        if(naEuroWlewo.isSelected()) 
        walutaPrawo.setText(naEuroWlewo.getText());
    }//GEN-LAST:event_naEuroWlewoActionPerformed

    private void naDolaryWlewoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naDolaryWlewoActionPerformed
        String waluta = "";
        if(naDolaryWlewo.isSelected()) 
        walutaPrawo.setText(naDolaryWlewo.getText());
    }//GEN-LAST:event_naDolaryWlewoActionPerformed

    private void naRubleWlewoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naRubleWlewoActionPerformed
        String waluta = "";
        if(naRubleWlewo.isSelected()) 
        walutaPrawo.setText(naRubleWlewo.getText());
    }//GEN-LAST:event_naRubleWlewoActionPerformed

    private double wyborPrzelicznikaZlewej(){
        double wybranyPrzelicznikLewy = 1.0f;
        if(naZłoteWprawo.isSelected()) wybranyPrzelicznikLewy = Zloty;
        else if(naEuroWprawo.isSelected()) wybranyPrzelicznikLewy = Euro;
        else if(naDolaryWprawo.isSelected()) wybranyPrzelicznikLewy = Dolar;
        else if(naRubleWprawo.isSelected()) wybranyPrzelicznikLewy = Rubel;
        return wybranyPrzelicznikLewy;
    }
    
        private double wyborPrzelicznikaZprawej(){
        double wybranyPrzelicznikPrawy = 1.0f;
        if(naZłoteWlewo.isSelected()) wybranyPrzelicznikPrawy = Zloty;
        else if(naEuroWlewo.isSelected()) wybranyPrzelicznikPrawy = Euro;
        else if(naDolaryWlewo.isSelected()) wybranyPrzelicznikPrawy = Dolar;
        else if(naRubleWlewo.isSelected()) wybranyPrzelicznikPrawy = Rubel;
        return wybranyPrzelicznikPrawy;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Konwerter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Konwerter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Konwerter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Konwerter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Konwerter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton naDolaryWlewo;
    private javax.swing.JRadioButton naDolaryWprawo;
    private javax.swing.JRadioButton naEuroWlewo;
    private javax.swing.JRadioButton naEuroWprawo;
    private javax.swing.JRadioButton naRubleWlewo;
    private javax.swing.JRadioButton naRubleWprawo;
    private javax.swing.JRadioButton naZłoteWlewo;
    private javax.swing.JRadioButton naZłoteWprawo;
    private javax.swing.JButton przeliczWlewo;
    private javax.swing.JButton przeliczWprawo;
    private javax.swing.JLabel walutaLewo;
    private javax.swing.JLabel walutaPrawo;
    private javax.swing.ButtonGroup walutyZlewej;
    private javax.swing.ButtonGroup walutyZprawej;
    private javax.swing.JTextField wejscie;
    private javax.swing.JTextField wyjscie;
    // End of variables declaration//GEN-END:variables
}
